repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0  # Use the latest stable version
    hooks:
      - id: black
        language_version: python3.13  # Adjust to your Python version

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the latest stable version
    hooks:
      - id: isort
        language_version: python3.13  # Adjust to your Python version
