name: Continuous Integration

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write permissions to the GITHUB_TOKEN
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Adjust to your Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit hooks
        id: run_pre_commit
        run: |
          pre-commit run --all-files || exit_code=$?
          echo "::set-output name=exit_code::$exit_code"
      - name: Commit and push changes
        if: steps.run_pre_commit.outputs.exit_code == '1'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Apply formatting fixes via pre-commit"
          git push
