name: Monthly issue metrics Month to Today
on:
  workflow_dispatch:
  # schedule:
  #  - cron: "3 2 1 * *"

permissions:
  contents: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read
    steps:
      - name: Get dates for last month
        shell: bash
        run: |
          # Calculate the first day of this month
          first_day=$(date -d "this month" +%Y-%m-01)

          # Calculate the last day of the previous month
          last_day=$(date -d "$today" +%Y-%m-%d)

          #Set an environment variable with the date range
          echo "$first_day..$last_day"
          echo "last_month=$first_day..$last_day" >> "$GITHUB_ENV"

      - name: Run issue-metrics tool
        uses: github/issue-metrics@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEARCH_QUERY: 'repo:mikeybob/demonlab-dashboard is:issue state:open OR or label:"Backend Design Change" label:"Database design change" OR label:"Frontend design change" OR label:enhancement or label:"Feature Request" created:${{ env.last_month }}'

      - name: Create issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Monthly issue metrics report
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./issue_metrics.md
