name: Change Demon Message
on:
 workflow_dispatch:
 #schedule:
    #- cron: '*/5 * * * *'
jobs:
  ping_matrix:
   runs-on: ubuntu-latest
   steps:
     - name: send message
       uses: s3krit/matrix-message-action@v0.0.3
       with:
         room_id: ${{ secrets.MATRIX_ROOM_ID }}
         access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
         message: "(i) Backups of metrics have been re-instated. Barad-dûr is running."
         server: "demonlab.net"
